=== MiilUCL/dcouvr/sesam/data_model/validator/validation_schemas/event_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#", 
    "$id": "https://sesam.be/validation_schemas/event_schema.json", 
    "title":"Event", 
    "description": "schema.org compliant description of a cultural Event", 
    "type":"object", 
    "properties" : {
        "@context": {
            "description": "obligatory schema.org element", 
            "type":"string"
        }, 
        "@type": {
            "description": "obligatory schema.org element", 
            "type":"string"
        }, 
        "identifier":{
            "description" : "identifier of Event object in SESAM database", 
            "type":"integer"
        }, 
        "name":{
            "description": "the name of the event",
            "type":"string"
        }, 
        "keywords":{
            "description": "associated categories of cultural content", 
            "type":"array", 
            "items": {
                "type": "object", 
                "$ref": "#/$defs/keyword"
            }
        }, 
        "location":{
            "description": "associated geographical area", 
            "type":"object", 
            "$ref": "#/$defs/place"
        }, 
        "audience":{
            "description": "associated target audience groups", 
            "type":"array", 
            "items":{
                "type":"object",
                "$ref": "#/$defs/audience"
            }
        }, 
        "organizer":{
            "description": "organizer of the event", 
            "type":"object", 
            "$ref": "#/$defs/organizer"
        }, 
        "description":{
            "description": "description of the Event", 
            "type":"string"
        }, 
        "startDate":{
            "description": "start date (datetime isoformat string) of the event", 
            "type":"string"
        }, 
        "endDate":{
            "description": "start date (datetime isoformat string) of the event",
            "type":"string"
        },
        "sameAs":{
            "description": "link to Event webpage on third party website",
            "type":"string"
        }
    }, 
    "required": ["@type","identifier", "name", "sameAs"], 

    "$defs" : {
        "keyword" : {
            "$id":"validation_schemas/keywords_schema.json", 
            "$schema" : "http://json-schema.org/draft-07/schema#", 
            "title" : "Keywords",
            "description": "keywords of a creator, expressing categories of cultural products", 
            "type":"object", 
            "properties": {
                "@type": {"type":"string", "description": "obligatory schema.org element"},
                "name":{"type":"string", "description": "name of the category of cultural product or content"},
                "termCode":{"type":"string", "description": "termcode associated to category of cultural product or content"}, 
                "inDefinedTermSet":{"type":"string", "description":"url to the termSet defining the correspondance between names and termCodes for categories of cultural products"}
            }, 
            "required":["@type","name", "termCode", "inDefinedTermSet"], 
            "additionalProperties":false
        }, 
        "place":{
            "$id":"validation_schemas/place_schema.json", 
            "$schema" : "http://json-schema.org/draft-07/schema#", 
            "title":"Place",
            "description":"geographical area associated to operator",
            "type":"object",
            "properties": {
                "@type": {"type":"array", "items":{"type":"string"}, "description": "obligatory schema.org element"},
                "name":{"type":"string", "description":"name of the geographical area"},
                "termCode":{"type":"string", "description":"termCode associated to the geographical area"}, 
                "inDefinedTermSet":{"type":"string", "description":"url to the termSet defining the correspondance between names and termCodes for geographical areas"}
            }, 
            "required":["@type","name", "termCode", "inDefinedTermSet"], 
            "additionalProperties":false
        }, 
        "audience":{
            "$id":"validation_schemas/audience_schema.json", 
            "$schema" : "http://json-schema.org/draft-07/schema#", 
            "title":"Audience",
            "description":"group of target audience associated to event",
            "type":"object",
            "properties": {
                "@type": {"type":"array", "items":{"type":"string"}, "description": "obligatory schema.org element"},
                "name":{"type":"string", "description":"name of the target audience group"},
                "termCode":{"type":"string", "description":"termCode associated to the audience group"}, 
                "inDefinedTermSet":{"type":"string", "description":"url to the termSet defining the correspondance between names and termCodes for target audience groups"}
            }, 
            "required":["@type","name", "termCode", "inDefinedTermSet"], 
            "additionalProperties":false
        }, 
        "organizer":{
            "$id":"validation_schemas/organizer_schema.json", 
            "$schema" : "http://json-schema.org/draft-07/schema#", 
            "title":"Organizer",
            "description":"organizer of an event",
            "type":"object",
            "properties": {
                "@type":{"type":"string", "description": "obligatory schema.org element"}, 
                "identifier":{"type":"integer", "description":"identifier of the operator that organizes the event in the SESAM supporting DBs"}, 
                "name":{"type":"string", "description":"name of the organizer"}
            }, 
            "required":["@type","identifier"], 
            "additionalProperties":false
        }
    }
}

=== MiilUCL/dcouvr/sesam/data_model/tests_results/test_event.json
{
    "@context": "https://schema.org",
    "@type": "Event",
    "identifier": 11713,
    "sameAs": "www.sport.be",
    "name": "bbb",
    "keywords": [
        {
            "@type": "DefinedTerm",
            "name": "SPORTS",
            "termCode": "CAT15-00",
            "inDefinedTermSet": "https://tinyurl.com/sesam-categories"
        }
    ],
    "location": {
        "@type": [
            "Place",
            "DefinedTerm"
        ],
        "name": "Mons",
        "termCode": "LOC12",
        "inDefinedTermSet": "https://tinyurl.com/sesam-areas"
    },
    "audience": [
        {
            "@type": [
                "Audience",
                "DefinedTerm"
            ],
            "name": "Amis",
            "termCode": "AUD01",
            "inDefinedTermSet": "https://tinyurl.com/sesam-audiences"
        },
        {
            "@type": [
                "Audience",
                "DefinedTerm"
            ],
            "name": "Conjoint",
            "termCode": "AUD02",
            "inDefinedTermSet": "https://tinyurl.com/sesam-categories"
        }
    ],
    "organizer": {
        "@type": "Organization",
        "identifier": 1001,
        "name": "ccc"
    },
    "startDate": "2024-01-04",
    "description": "du sport"
}
