=== MiilUCL/dcouvr/sesam/data_model/validator/validation_schemas/profile_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id" : "https://sesam.be/validation_schemas/profile_schema.json", 
    "title" : "Profile",
    "description": "The profile of a SESAM user", 
    "type":"object",
    "properties": {
        "identifier" : {
            "description": "The unique identifier of the SESAM user",
            "type": "integer"
        }, 
        "timestamp": {
            "description": "The timestamp (datetime isoformat string) of the latest modification to the profile", 
            "type": "string"
        }, 
        "versioning":{
            "description": "The url to the specification of the SESAM ontology used",
            "type":"string"
        },
        "preferences": {
            "description": "The cultural preferences of the user", 
            "type":"object",
            "$ref": "#/$defs/preferences"
        }
    },
    "required": ["identifier", "timestamp", "preferences"], 
    "additionalProperties": false,


    "$defs": {
        "preferences": {
            "$id": "/validation_schemas/preferences_schema.json",
            "$schema" : "http://json-schema.org/draft-07/schema#", 
            "title" : "Preferences",
            "description": "The cultural preferences of a SESAM user", 
            "type":"object", 
            "properties": {
                "categories" : {
                    "description": "list of objects expressing preferences for categories of cultural contents",
                    "type":"array", 
                    "items" : {
                        "type":"object",
                        "$ref": "#/$defs/generic_preference"
                    }
                },
                "audiences" : {
                    "description": "list of objects expressing preferences for target audiences",
                    "type":"array", 
                    "items" : {
                        "type":"object",
                        "$ref": "#/$defs/generic_preference"
                    }
                }, 
                "areas" : {
                    "description": "list of objects expressing preferences for geographical areas",
                    "type":"array", 
                    "items" : {
                        "type":"object",
                        "$ref": "#/$defs/generic_preference"
                    }
                },
                "culturalProducts" : {
                    "description": "list of objects expressing preferences for cultural products",
                    "type":"array", 
                    "items" : {
                        "type":"object",
                        "$ref": "#/$defs/specific_preference"
                    }
                },
                "culturalOperators" : {
                    "description": "list of objects expressing preferences for cultural opertators",
                    "type":"array", 
                    "items" : {
                        "type":"object",
                        "$ref": "#/$defs/specific_preference"
                    }
                },
                "culturalCreators" : {
                    "description": "list of objects expressing preferences for cultural creators",
                    "type":"array", 
                    "items" : {
                        "type":"object",
                        "$ref": "#/$defs/specific_preference"
                    }
                }
            }, 
            "additionalProperties": false
        }, 



        "generic_preference" : {
            "$schema": "http://json-schema.org/draft-07/schema#",
            "$id" : "/validation_schemas/generic_preference_schema.json",
            "type": "object", 
            "properties": {
                "name":{"type":"string", "description":"name of the preference expressed"}, 
                "termCode":{"type":"string", "description":"associated termCode"},
                "inDefinedTermSet":{"type":"string", "description":"url to the termSet defining the correspondance between names and termcodes for this preference"},
                "rating":{"type":"integer", "description":"rating attributed to this preference by the user, scale from 1 to 5"}, 
                "timestamp":{"type":"string", "description":"The timestamp (datetime isoformat string) of the addition of this prefernce"}
            }, 
            "required": ["name", "termCode", "inDefinedTermSet", "rating", "timestamp"], 
            "additionalProperties": false
        }, 

        "specific_preference" : {
            "$schema": "http://json-schema.org/draft-07/schema#",
            "$id" : "/validation_schemas/specific_preference_schema.json",
            "type":"object", 
            "properties":{
                "identifier":{"type":"integer", "description":"identfier of the item in the SESAM supporting DBs"}, 
                "name":{"type":"string", "description": "name of the item"}, 
                "rating":{"type":"integer", "description":"rating attributed to this preference by the user, scale from 1 to 5"}, 
                "timestamp":{"type":"string", "description":"rating attributed to this preference by the user, scale from 1 to 5"}, 
                "type":{"type":"string", "description":"type of the item (only applies to Cultural Products"}
            },
            "required":["identifier", "name", "rating", "timestamp"], 
            "additionalProperties": false
        }
    }
}

=== MiilUCL/dcouvr/sesam/data_model/profile_examples/example10.json
{
    "identifier": 844,
    "versioning": "https://miilucl.github.io/dcouvr/sesam/sesam_v0/profile_schema.html",
    "timestamp": "2024-01-21T18:47:34.765836",
    "preferences": {
        "categories": [
            {
                "name": "STAGES / COURS - art plastique",
                "termCode": "CAT09-02",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam/sesam_v0/termSets/DefinedTermSet_categories.csv",
                "rating": 3,
                "timestamp": "2024-01-21T18:47:34.761847"
            }
        ],
        "audiences": [
            {
                "name": "Enfants (7 à 11 ans)",
                "termCode": "AUD04",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam/sesam_v0/termSets/DefinedTermSet_audience.csv",
                "rating": 4,
                "timestamp": "2024-01-21T18:47:34.762844"
            }
        ],
        "areas": [
            {
                "name": "La Louvière",
                "termCode": "LOC16",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam/sesam_v0/termSets/DefinedTermSet_location.csv",
                "rating": 5,
                "timestamp": "2024-01-21T18:47:34.763842"
            },
            {
                "name": "province de Namur",
                "termCode": "LOC04",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam/sesam_v0/termSets/DefinedTermSet_location.csv",
                "rating": 3,
                "timestamp": "2024-01-21T18:47:34.764839"
            }
        ],
        "culturalProducts": [
            {
                "identifier": 10002,
                "name": "Cro'Medy Club #1",
                "type": "Event",
                "rating": 1,
                "timestamp": "2024-01-21T18:47:34.764839"
            },
            {
                "identifier": 10002,
                "name": "Cro'Medy Club #1",
                "type": "Event",
                "rating": 4,
                "timestamp": "2024-01-21T18:47:34.764839"
            },
            {
                "identifier": 10009,
                "name": "New project : KAIS FRIHAT QUARTET",
                "type": "Event",
                "rating": 3,
                "timestamp": "2024-01-21T18:47:34.764839"
            },
            {
                "identifier": 10008,
                "name": "\"Les Bonnes\" de Jean genet",
                "type": "Event",
                "rating": 5,
                "timestamp": "2024-01-21T18:47:34.764839"
            },
            {
                "identifier": 10008,
                "name": "\"Les Bonnes\" de Jean genet",
                "type": "Event",
                "rating": 1,
                "timestamp": "2024-01-21T18:47:34.764839"
            }
        ],
        "culturalOperators": [
            {
                "identifier": 20004,
                "name": "Plaza",
                "rating": 4,
                "timestamp": "2024-01-21T18:47:34.765836"
            },
            {
                "identifier": 20006,
                "name": "Palais des Beaux-Arts de Bruxelles - Bozar",
                "rating": 2,
                "timestamp": "2024-01-21T18:47:34.765836"
            }
        ],
        "culturalCreators": [
            {
                "identifier": 30001,
                "name": "Girls in Hawaii",
                "rating": 4,
                "timestamp": "2024-01-21T18:47:34.765836"
            },
            {
                "identifier": 30007,
                "name": "Emilie Dequenne",
                "rating": 5,
                "timestamp": "2024-01-21T18:47:34.765836"
            }
        ]
    }
}

=== MiilUCL/dcouvr/sesam/data_model/profile_examples/example7.json
{
    "identifier": 517,
    "versioning": "https://miilucl.github.io/dcouvr/sesam_v0/profile_schema.html",
    "timestamp": "2024-01-17T17:56:40.510501",
    "preferences": {
        "categories": [],
        "audiences": [
            {
                "name": "Séniors",
                "termCode": "AUD07",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam_v0/termSets/DefinedTermSet_audience.csv",
                "rating": 3,
                "timestamp": "2024-01-17T17:56:40.506023"
            },
            {
                "name": "Séniors",
                "termCode": "AUD07",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam_v0/termSets/DefinedTermSet_audience.csv",
                "rating": 1,
                "timestamp": "2024-01-17T17:56:40.507089"
            }
        ],
        "areas": [
            {
                "name": "Verviers",
                "termCode": "LOC11",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam_v0/termSets/DefinedTermSet_location.csv",
                "rating": 5,
                "timestamp": "2024-01-17T17:56:40.508236"
            },
            {
                "name": "Arlon",
                "termCode": "LOC24",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam_v0/termSets/DefinedTermSet_location.csv",
                "rating": 5,
                "timestamp": "2024-01-17T17:56:40.508236"
            }
        ],
        "culturalProducts": [
            {
                "identifier": 10005,
                "name": "Vos livres ont la parole !",
                "type": "Event",
                "rating": 1,
                "timestamp": "2024-01-17T17:56:40.508236"
            },
            {
                "identifier": 10009,
                "name": "New project : KAIS FRIHAT QUARTET",
                "type": "Event",
                "rating": 2,
                "timestamp": "2024-01-17T17:56:40.509505"
            },
            {
                "identifier": 10008,
                "name": "\"Les Bonnes\" de Jean genet",
                "type": "Event",
                "rating": 3,
                "timestamp": "2024-01-17T17:56:40.509505"
            },
            {
                "identifier": 10004,
                "name": "Explo - Bretagne",
                "type": "Event",
                "rating": 2,
                "timestamp": "2024-01-17T17:56:40.509505"
            },
            {
                "identifier": 10008,
                "name": "\"Les Bonnes\" de Jean genet",
                "type": "Event",
                "rating": 4,
                "timestamp": "2024-01-17T17:56:40.509505"
            }
        ],
        "culturalOperators": [
            {
                "identifier": 20004,
                "name": "Plaza",
                "rating": 4,
                "timestamp": "2024-01-17T17:56:40.509505"
            }
        ],
        "culturalCreators": [
            {
                "identifier": 30015,
                "name": "Zakia Khattabi",
                "rating": 4,
                "timestamp": "2024-01-17T17:56:40.509505"
            },
            {
                "identifier": 30016,
                "name": "Jean Merveille",
                "rating": 3,
                "timestamp": "2024-01-17T17:56:40.509505"
            },
            {
                "identifier": 30016,
                "name": "Jean Merveille",
                "rating": 2,
                "timestamp": "2024-01-17T17:56:40.510501"
            }
        ]
    }
}

=== MiilUCL/dcouvr/sesam/data_model/profile_examples/example2.json
{
    "identifier": 637,
    "versioning": "https://miilucl.github.io/dcouvr/sesam_v0/profile_schema.html",
    "timestamp": "2024-01-17T17:56:40.476776",
    "preferences": {
        "categories": [
            {
                "name": "CONCERTS - festival",
                "termCode": "CAT01-10",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam_v0/termSets/DefinedTermSet_categories.csv",
                "rating": 1,
                "timestamp": "2024-01-17T17:56:40.472197"
            }
        ],
        "audiences": [
            {
                "name": "Séniors",
                "termCode": "AUD07",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam_v0/termSets/DefinedTermSet_audience.csv",
                "rating": 1,
                "timestamp": "2024-01-17T17:56:40.473154"
            },
            {
                "name": "Enfants (0 à 6 ans)",
                "termCode": "AUD03",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam_v0/termSets/DefinedTermSet_audience.csv",
                "rating": 5,
                "timestamp": "2024-01-17T17:56:40.474150"
            }
        ],
        "areas": [
            {
                "name": "Nivelles",
                "termCode": "LOC09",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam_v0/termSets/DefinedTermSet_location.csv",
                "rating": 4,
                "timestamp": "2024-01-17T17:56:40.475148"
            }
        ],
        "culturalProducts": [
            {
                "identifier": 10008,
                "name": "\"Les Bonnes\" de Jean genet",
                "type": "Event",
                "rating": 5,
                "timestamp": "2024-01-17T17:56:40.475148"
            },
            {
                "identifier": 10003,
                "name": "L'église Saint-Médard de Jodoigne",
                "type": "Event",
                "rating": 2,
                "timestamp": "2024-01-17T17:56:40.475148"
            },
            {
                "identifier": 10004,
                "name": "Explo - Bretagne",
                "type": "Event",
                "rating": 3,
                "timestamp": "2024-01-17T17:56:40.475148"
            }
        ],
        "culturalOperators": [
            {
                "identifier": 20002,
                "name": "Maison de la Jeunesse de Woluwe-Saint-Lambert",
                "rating": 2,
                "timestamp": "2024-01-17T17:56:40.475148"
            },
            {
                "identifier": 20003,
                "name": "Extension ULB de Jodoigne & Environs",
                "rating": 3,
                "timestamp": "2024-01-17T17:56:40.475148"
            },
            {
                "identifier": 20006,
                "name": "Palais des Beaux-Arts de Bruxelles - Bozar",
                "rating": 1,
                "timestamp": "2024-01-17T17:56:40.475148"
            },
            {
                "identifier": 20003,
                "name": "Extension ULB de Jodoigne & Environs",
                "rating": 3,
                "timestamp": "2024-01-17T17:56:40.475148"
            },
            {
                "identifier": 20008,
                "name": "Centre Culturel d'Amay",
                "rating": 5,
                "timestamp": "2024-01-17T17:56:40.475148"
            }
        ],
        "culturalCreators": [
            {
                "identifier": 30001,
                "name": "Girls in Hawaii",
                "rating": 3,
                "timestamp": "2024-01-17T17:56:40.475148"
            },
            {
                "identifier": 30002,
                "name": "Jacques Brel",
                "rating": 1,
                "timestamp": "2024-01-17T17:56:40.475148"
            },
            {
                "identifier": 30005,
                "name": "iliona",
                "rating": 2,
                "timestamp": "2024-01-17T17:56:40.476686"
            },
            {
                "identifier": 30017,
                "name": "David Van Reybroeck",
                "rating": 2,
                "timestamp": "2024-01-17T17:56:40.476776"
            }
        ]
    }
}
