=== MiilUCL/dcouvr/sesam/data_model/validator/validation_schemas/profile_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id" : "https://sesam.be/validation_schemas/profile_schema.json", 
    "title" : "Profile",
    "description": "The profile of a SESAM user", 
    "type":"object",
    "properties": {
        "identifier" : {
            "description": "The unique identifier of the SESAM user",
            "type": "integer"
        }, 
        "timestamp": {
            "description": "The timestamp (datetime isoformat string) of the latest modification to the profile", 
            "type": "string"
        }, 
        "versioning":{
            "description": "The url to the specification of the SESAM ontology used",
            "type":"string"
        },
        "preferences": {
            "description": "The cultural preferences of the user", 
            "type":"object",
            "$ref": "#/$defs/preferences"
        }
    },
    "required": ["identifier", "timestamp", "preferences"], 
    "additionalProperties": false,


    "$defs": {
        "preferences": {
            "$id": "/validation_schemas/preferences_schema.json",
            "$schema" : "http://json-schema.org/draft-07/schema#", 
            "title" : "Preferences",
            "description": "The cultural preferences of a SESAM user", 
            "type":"object", 
            "properties": {
                "categories" : {
                    "description": "list of objects expressing preferences for categories of cultural contents",
                    "type":"array", 
                    "items" : {
                        "type":"object",
                        "$ref": "#/$defs/generic_preference"
                    }
                },
                "audiences" : {
                    "description": "list of objects expressing preferences for target audiences",
                    "type":"array", 
                    "items" : {
                        "type":"object",
                        "$ref": "#/$defs/generic_preference"
                    }
                }, 
                "areas" : {
                    "description": "list of objects expressing preferences for geographical areas",
                    "type":"array", 
                    "items" : {
                        "type":"object",
                        "$ref": "#/$defs/generic_preference"
                    }
                },
                "culturalProducts" : {
                    "description": "list of objects expressing preferences for cultural products",
                    "type":"array", 
                    "items" : {
                        "type":"object",
                        "$ref": "#/$defs/specific_preference"
                    }
                },
                "culturalOperators" : {
                    "description": "list of objects expressing preferences for cultural opertators",
                    "type":"array", 
                    "items" : {
                        "type":"object",
                        "$ref": "#/$defs/specific_preference"
                    }
                },
                "culturalCreators" : {
                    "description": "list of objects expressing preferences for cultural creators",
                    "type":"array", 
                    "items" : {
                        "type":"object",
                        "$ref": "#/$defs/specific_preference"
                    }
                }
            }, 
            "additionalProperties": false
        }, 



        "generic_preference" : {
            "$schema": "http://json-schema.org/draft-07/schema#",
            "$id" : "/validation_schemas/generic_preference_schema.json",
            "type": "object", 
            "properties": {
                "name":{"type":"string", "description":"name of the preference expressed"}, 
                "termCode":{"type":"string", "description":"associated termCode"},
                "inDefinedTermSet":{"type":"string", "description":"url to the termSet defining the correspondance between names and termcodes for this preference"},
                "rating":{"type":"integer", "description":"rating attributed to this preference by the user, scale from 1 to 5"}, 
                "timestamp":{"type":"string", "description":"The timestamp (datetime isoformat string) of the addition of this prefernce"}
            }, 
            "required": ["name", "termCode", "inDefinedTermSet", "rating", "timestamp"], 
            "additionalProperties": false
        }, 

        "specific_preference" : {
            "$schema": "http://json-schema.org/draft-07/schema#",
            "$id" : "/validation_schemas/specific_preference_schema.json",
            "type":"object", 
            "properties":{
                "identifier":{"type":"integer", "description":"identfier of the item in the SESAM supporting DBs"}, 
                "name":{"type":"string", "description": "name of the item"}, 
                "rating":{"type":"integer", "description":"rating attributed to this preference by the user, scale from 1 to 5"}, 
                "timestamp":{"type":"string", "description":"rating attributed to this preference by the user, scale from 1 to 5"}, 
                "type":{"type":"string", "description":"type of the item (only applies to Cultural Products"}
            },
            "required":["identifier", "name", "rating", "timestamp"], 
            "additionalProperties": false
        }
    }
}

=== MiilUCL/dcouvr/sesam/data_model/profile_examples/example6.json
{
    "identifier": 535,
    "versioning": "https://miilucl.github.io/dcouvr/sesam/sesam_v0/profile_schema.html",
    "timestamp": "2024-01-21T18:47:34.738502",
    "preferences": {
        "categories": [
            {
                "name": "SOIRÉES - retro (rock, swing)",
                "termCode": "CAT10-18",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam/sesam_v0/termSets/DefinedTermSet_categories.csv",
                "rating": 3,
                "timestamp": "2024-01-21T18:47:34.733514"
            },
            {
                "name": "FÊTES / FOLKLORE",
                "termCode": "CAT14-00",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam/sesam_v0/termSets/DefinedTermSet_categories.csv",
                "rating": 5,
                "timestamp": "2024-01-21T18:47:34.734513"
            },
            {
                "name": "THÉATRE / SPECTACLES - comédie musicale",
                "termCode": "CAT02-05",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam/sesam_v0/termSets/DefinedTermSet_categories.csv",
                "rating": 2,
                "timestamp": "2024-01-21T18:47:34.735509"
            }
        ],
        "audiences": [],
        "areas": [
            {
                "name": "La Louvière",
                "termCode": "LOC16",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam/sesam_v0/termSets/DefinedTermSet_location.csv",
                "rating": 4,
                "timestamp": "2024-01-21T18:47:34.736507"
            },
            {
                "name": "province du Brabant wallon",
                "termCode": "LOC05",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam/sesam_v0/termSets/DefinedTermSet_location.csv",
                "rating": 5,
                "timestamp": "2024-01-21T18:47:34.737507"
            }
        ],
        "culturalProducts": [],
        "culturalOperators": [
            {
                "identifier": 20005,
                "name": "Librairie Toutes Directions",
                "rating": 4,
                "timestamp": "2024-01-21T18:47:34.737507"
            },
            {
                "identifier": 20004,
                "name": "Plaza",
                "rating": 5,
                "timestamp": "2024-01-21T18:47:34.737507"
            },
            {
                "identifier": 20008,
                "name": "Centre Culturel d'Amay",
                "rating": 1,
                "timestamp": "2024-01-21T18:47:34.737507"
            },
            {
                "identifier": 20006,
                "name": "Palais des Beaux-Arts de Bruxelles - Bozar",
                "rating": 5,
                "timestamp": "2024-01-21T18:47:34.737507"
            },
            {
                "identifier": 20008,
                "name": "Centre Culturel d'Amay",
                "rating": 4,
                "timestamp": "2024-01-21T18:47:34.737507"
            }
        ],
        "culturalCreators": [
            {
                "identifier": 30002,
                "name": "Jacques Brel",
                "rating": 2,
                "timestamp": "2024-01-21T18:47:34.737507"
            },
            {
                "identifier": 30013,
                "name": "Cirque Nicolas Bouglione",
                "rating": 1,
                "timestamp": "2024-01-21T18:47:34.737507"
            },
            {
                "identifier": 30010,
                "name": "Belgian Red Flames",
                "rating": 3,
                "timestamp": "2024-01-21T18:47:34.738502"
            },
            {
                "identifier": 30007,
                "name": "Emilie Dequenne",
                "rating": 3,
                "timestamp": "2024-01-21T18:47:34.738502"
            },
            {
                "identifier": 30006,
                "name": "Lukas Dhont",
                "rating": 2,
                "timestamp": "2024-01-21T18:47:34.738502"
            }
        ]
    }
}

=== MiilUCL/dcouvr/sesam/data_model/profile_examples/example4.json
{
    "identifier": 855,
    "versioning": "https://miilucl.github.io/dcouvr/sesam/sesam_v0/profile_schema.html",
    "timestamp": "2024-01-21T18:47:34.721030",
    "preferences": {
        "categories": [
            {
                "name": "FÊTES / FOLKLORE",
                "termCode": "CAT14-00",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam/sesam_v0/termSets/DefinedTermSet_categories.csv",
                "rating": 1,
                "timestamp": "2024-01-21T18:47:34.717041"
            },
            {
                "name": "CONCERTS - reggae / ragga / dub / ska",
                "termCode": "CAT01-16",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam/sesam_v0/termSets/DefinedTermSet_categories.csv",
                "rating": 1,
                "timestamp": "2024-01-21T18:47:34.718038"
            },
            {
                "name": "MARCHÉS ET BROCANTES - marché de noël",
                "termCode": "CAT13-05",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam/sesam_v0/termSets/DefinedTermSet_categories.csv",
                "rating": 4,
                "timestamp": "2024-01-21T18:47:34.719035"
            },
            {
                "name": "FÊTES / FOLKLORE - festivités",
                "termCode": "CAT14-03",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam/sesam_v0/termSets/DefinedTermSet_categories.csv",
                "rating": 5,
                "timestamp": "2024-01-21T18:47:34.720033"
            }
        ],
        "audiences": [],
        "areas": [],
        "culturalProducts": [
            {
                "identifier": 10002,
                "name": "Cro'Medy Club #1",
                "type": "Event",
                "rating": 2,
                "timestamp": "2024-01-21T18:47:34.720033"
            }
        ],
        "culturalOperators": [
            {
                "identifier": 20004,
                "name": "Plaza",
                "rating": 1,
                "timestamp": "2024-01-21T18:47:34.720033"
            },
            {
                "identifier": 20005,
                "name": "Librairie Toutes Directions",
                "rating": 3,
                "timestamp": "2024-01-21T18:47:34.720033"
            },
            {
                "identifier": 20009,
                "name": "The Music Village",
                "rating": 4,
                "timestamp": "2024-01-21T18:47:34.720033"
            },
            {
                "identifier": 20001,
                "name": "Blues-sphere Bar",
                "rating": 4,
                "timestamp": "2024-01-21T18:47:34.721030"
            }
        ],
        "culturalCreators": [
            {
                "identifier": 30001,
                "name": "Girls in Hawaii",
                "rating": 2,
                "timestamp": "2024-01-21T18:47:34.721030"
            },
            {
                "identifier": 30002,
                "name": "Jacques Brel",
                "rating": 5,
                "timestamp": "2024-01-21T18:47:34.721030"
            },
            {
                "identifier": 30016,
                "name": "Jean Merveille",
                "rating": 3,
                "timestamp": "2024-01-21T18:47:34.721030"
            },
            {
                "identifier": 30004,
                "name": "Damso",
                "rating": 1,
                "timestamp": "2024-01-21T18:47:34.721030"
            }
        ]
    }
}

=== MiilUCL/dcouvr/sesam/data_model/profile_examples/example3.json
{
    "identifier": 842,
    "versioning": "https://miilucl.github.io/dcouvr/sesam_v0/profile_schema.html",
    "timestamp": "2024-01-17T17:56:40.479958",
    "preferences": {
        "categories": [],
        "audiences": [],
        "areas": [
            {
                "name": "Thuin",
                "termCode": "LOC14",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam_v0/termSets/DefinedTermSet_location.csv",
                "rating": 1,
                "timestamp": "2024-01-17T17:56:40.477960"
            }
        ],
        "culturalProducts": [],
        "culturalOperators": [
            {
                "identifier": 20002,
                "name": "Maison de la Jeunesse de Woluwe-Saint-Lambert",
                "rating": 4,
                "timestamp": "2024-01-17T17:56:40.478965"
            },
            {
                "identifier": 20003,
                "name": "Extension ULB de Jodoigne & Environs",
                "rating": 1,
                "timestamp": "2024-01-17T17:56:40.478965"
            },
            {
                "identifier": 20001,
                "name": "Blues-sphere Bar",
                "rating": 2,
                "timestamp": "2024-01-17T17:56:40.478965"
            },
            {
                "identifier": 20007,
                "name": "Centre Culturel de Chênée",
                "rating": 4,
                "timestamp": "2024-01-17T17:56:40.478965"
            }
        ],
        "culturalCreators": [
            {
                "identifier": 30005,
                "name": "iliona",
                "rating": 5,
                "timestamp": "2024-01-17T17:56:40.478965"
            },
            {
                "identifier": 30014,
                "name": "Jean Van Hamme",
                "rating": 4,
                "timestamp": "2024-01-17T17:56:40.478965"
            },
            {
                "identifier": 30008,
                "name": "Guillermo Guiz",
                "rating": 1,
                "timestamp": "2024-01-17T17:56:40.478965"
            },
            {
                "identifier": 30013,
                "name": "Cirque Nicolas Bouglione",
                "rating": 3,
                "timestamp": "2024-01-17T17:56:40.478965"
            },
            {
                "identifier": 30010,
                "name": "Belgian Red Flames",
                "rating": 3,
                "timestamp": "2024-01-17T17:56:40.479958"
            }
        ]
    }
}

=== MiilUCL/dcouvr/sesam/data_model/profile_examples/example5.json
{
    "identifier": 574,
    "versioning": "https://miilucl.github.io/dcouvr/sesam_v0/profile_schema.html",
    "timestamp": "2024-01-17T17:56:40.495787",
    "preferences": {
        "categories": [],
        "audiences": [
            {
                "name": "Etudiants",
                "termCode": "AUD06",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam_v0/termSets/DefinedTermSet_audience.csv",
                "rating": 3,
                "timestamp": "2024-01-17T17:56:40.492304"
            },
            {
                "name": "Séniors",
                "termCode": "AUD07",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam_v0/termSets/DefinedTermSet_audience.csv",
                "rating": 5,
                "timestamp": "2024-01-17T17:56:40.493279"
            }
        ],
        "areas": [
            {
                "name": "province de Luxembourg",
                "termCode": "LOC06",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam_v0/termSets/DefinedTermSet_location.csv",
                "rating": 1,
                "timestamp": "2024-01-17T17:56:40.494248"
            },
            {
                "name": "province de Luxembourg",
                "termCode": "LOC06",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam_v0/termSets/DefinedTermSet_location.csv",
                "rating": 1,
                "timestamp": "2024-01-17T17:56:40.495247"
            }
        ],
        "culturalProducts": [],
        "culturalOperators": [
            {
                "identifier": 20002,
                "name": "Maison de la Jeunesse de Woluwe-Saint-Lambert",
                "rating": 4,
                "timestamp": "2024-01-17T17:56:40.495247"
            }
        ],
        "culturalCreators": [
            {
                "identifier": 30012,
                "name": "Céline Delbecq",
                "rating": 5,
                "timestamp": "2024-01-17T17:56:40.495787"
            },
            {
                "identifier": 30007,
                "name": "Emilie Dequenne",
                "rating": 1,
                "timestamp": "2024-01-17T17:56:40.495787"
            },
            {
                "identifier": 30009,
                "name": "Charlotte De Witte",
                "rating": 5,
                "timestamp": "2024-01-17T17:56:40.495787"
            },
            {
                "identifier": 30014,
                "name": "Jean Van Hamme",
                "rating": 5,
                "timestamp": "2024-01-17T17:56:40.495787"
            },
            {
                "identifier": 30006,
                "name": "Lukas Dhont",
                "rating": 1,
                "timestamp": "2024-01-17T17:56:40.495787"
            }
        ]
    }
}

=== MiilUCL/dcouvr/sesam/data_model/profile_examples/example8.json
{
    "identifier": 656,
    "versioning": "https://miilucl.github.io/dcouvr/sesam/sesam_v0/profile_schema.html",
    "timestamp": "2024-01-21T18:47:34.753429",
    "preferences": {
        "categories": [],
        "audiences": [
            {
                "name": "Etudiants",
                "termCode": "AUD06",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam/sesam_v0/termSets/DefinedTermSet_audience.csv",
                "rating": 3,
                "timestamp": "2024-01-21T18:47:34.750448"
            },
            {
                "name": "Conjoint",
                "termCode": "AUD02",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam/sesam_v0/termSets/DefinedTermSet_audience.csv",
                "rating": 1,
                "timestamp": "2024-01-21T18:47:34.751435"
            }
        ],
        "areas": [],
        "culturalProducts": [
            {
                "identifier": 10009,
                "name": "New project : KAIS FRIHAT QUARTET",
                "type": "Event",
                "rating": 4,
                "timestamp": "2024-01-21T18:47:34.752432"
            },
            {
                "identifier": 10003,
                "name": "L'église Saint-Médard de Jodoigne",
                "type": "Event",
                "rating": 4,
                "timestamp": "2024-01-21T18:47:34.752432"
            },
            {
                "identifier": 10007,
                "name": "Didier Laloy Dyad & Strings Quartet ",
                "type": "Event",
                "rating": 2,
                "timestamp": "2024-01-21T18:47:34.752432"
            }
        ],
        "culturalOperators": [
            {
                "identifier": 20005,
                "name": "Librairie Toutes Directions",
                "rating": 4,
                "timestamp": "2024-01-21T18:47:34.752432"
            },
            {
                "identifier": 20005,
                "name": "Librairie Toutes Directions",
                "rating": 2,
                "timestamp": "2024-01-21T18:47:34.752432"
            },
            {
                "identifier": 20009,
                "name": "The Music Village",
                "rating": 3,
                "timestamp": "2024-01-21T18:47:34.752432"
            }
        ],
        "culturalCreators": [
            {
                "identifier": 30017,
                "name": "David Van Reybroeck",
                "rating": 3,
                "timestamp": "2024-01-21T18:47:34.753429"
            },
            {
                "identifier": 30007,
                "name": "Emilie Dequenne",
                "rating": 5,
                "timestamp": "2024-01-21T18:47:34.753429"
            },
            {
                "identifier": 30004,
                "name": "Damso",
                "rating": 1,
                "timestamp": "2024-01-21T18:47:34.753429"
            },
            {
                "identifier": 30007,
                "name": "Emilie Dequenne",
                "rating": 4,
                "timestamp": "2024-01-21T18:47:34.753429"
            },
            {
                "identifier": 30005,
                "name": "iliona",
                "rating": 4,
                "timestamp": "2024-01-21T18:47:34.753429"
            }
        ]
    }
}

=== MiilUCL/dcouvr/sesam/data_model/profile_examples/example1.json
{
    "identifier": 641,
    "versioning": "https://miilucl.github.io/dcouvr/sesam/sesam_v0/profile_schema.html",
    "timestamp": "2024-01-21T18:47:34.690491",
    "preferences": {
        "categories": [
            {
                "name": "THÉATRE / SPECTACLES - professionnel",
                "termCode": "CAT02-02",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam/sesam_v0/termSets/DefinedTermSet_categories.csv",
                "rating": 2,
                "timestamp": "2024-01-21T18:47:34.672280"
            }
        ],
        "audiences": [],
        "areas": [
            {
                "name": "Philippeville",
                "termCode": "LOC22",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam/sesam_v0/termSets/DefinedTermSet_location.csv",
                "rating": 3,
                "timestamp": "2024-01-21T18:47:34.677068"
            },
            {
                "name": "Tournai",
                "termCode": "LOC15",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam/sesam_v0/termSets/DefinedTermSet_location.csv",
                "rating": 1,
                "timestamp": "2024-01-21T18:47:34.678065"
            },
            {
                "name": "Province de Liège",
                "termCode": "LOC02",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam/sesam_v0/termSets/DefinedTermSet_location.csv",
                "rating": 4,
                "timestamp": "2024-01-21T18:47:34.679062"
            }
        ],
        "culturalProducts": [
            {
                "identifier": 10004,
                "name": "Explo - Bretagne",
                "type": "Event",
                "rating": 3,
                "timestamp": "2024-01-21T18:47:34.684081"
            },
            {
                "identifier": 10008,
                "name": "\"Les Bonnes\" de Jean genet",
                "type": "Event",
                "rating": 5,
                "timestamp": "2024-01-21T18:47:34.684081"
            },
            {
                "identifier": 10005,
                "name": "Vos livres ont la parole !",
                "type": "Event",
                "rating": 1,
                "timestamp": "2024-01-21T18:47:34.685046"
            },
            {
                "identifier": 10004,
                "name": "Explo - Bretagne",
                "type": "Event",
                "rating": 3,
                "timestamp": "2024-01-21T18:47:34.685046"
            },
            {
                "identifier": 10003,
                "name": "L'église Saint-Médard de Jodoigne",
                "type": "Event",
                "rating": 3,
                "timestamp": "2024-01-21T18:47:34.685046"
            }
        ],
        "culturalOperators": [
            {
                "identifier": 20005,
                "name": "Librairie Toutes Directions",
                "rating": 3,
                "timestamp": "2024-01-21T18:47:34.690491"
            },
            {
                "identifier": 20005,
                "name": "Librairie Toutes Directions",
                "rating": 2,
                "timestamp": "2024-01-21T18:47:34.690491"
            },
            {
                "identifier": 20004,
                "name": "Plaza",
                "rating": 2,
                "timestamp": "2024-01-21T18:47:34.690491"
            },
            {
                "identifier": 20007,
                "name": "Centre Culturel de Chênée",
                "rating": 5,
                "timestamp": "2024-01-21T18:47:34.690491"
            },
            {
                "identifier": 20004,
                "name": "Plaza",
                "rating": 5,
                "timestamp": "2024-01-21T18:47:34.690491"
            }
        ],
        "culturalCreators": []
    }
}

=== MiilUCL/dcouvr/sesam/data_model/profile_examples/example9.json
{
    "identifier": 784,
    "versioning": "https://miilucl.github.io/dcouvr/sesam_v0/profile_schema.html",
    "timestamp": "2024-01-17T17:56:40.521221",
    "preferences": {
        "categories": [
            {
                "name": "CONCERTS - revue / danse cabaret",
                "termCode": "CAT01-17",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam_v0/termSets/DefinedTermSet_categories.csv",
                "rating": 1,
                "timestamp": "2024-01-17T17:56:40.519227"
            }
        ],
        "audiences": [],
        "areas": [
            {
                "name": "Dinant",
                "termCode": "LOC18",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam_v0/termSets/DefinedTermSet_location.csv",
                "rating": 4,
                "timestamp": "2024-01-17T17:56:40.520223"
            },
            {
                "name": "Mouscron",
                "termCode": "LOC21",
                "inDefinedTermSet": "https://miilucl.github.io/dcouvr/sesam_v0/termSets/DefinedTermSet_location.csv",
                "rating": 4,
                "timestamp": "2024-01-17T17:56:40.520223"
            }
        ],
        "culturalProducts": [
            {
                "identifier": 10003,
                "name": "L'église Saint-Médard de Jodoigne",
                "type": "Event",
                "rating": 5,
                "timestamp": "2024-01-17T17:56:40.521221"
            },
            {
                "identifier": 10002,
                "name": "Cro'Medy Club #1",
                "type": "Event",
                "rating": 3,
                "timestamp": "2024-01-17T17:56:40.521221"
            },
            {
                "identifier": 10006,
                "name": "Meet the artist: Baloji",
                "type": "Event",
                "rating": 5,
                "timestamp": "2024-01-17T17:56:40.521221"
            }
        ],
        "culturalOperators": [],
        "culturalCreators": [
            {
                "identifier": 30004,
                "name": "Damso",
                "rating": 5,
                "timestamp": "2024-01-17T17:56:40.521221"
            }
        ]
    }
}
